# Generated by Django 5.2.4 on 2025-07-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='영화 제목')),
                ('director', models.CharField(max_length=100, verbose_name='감독')),
                ('cast', models.CharField(max_length=200, verbose_name='주연')),
                ('genre', models.CharField(max_length=100, verbose_name='장르')),
                ('rating', models.IntegerField(choices=[(1, '1점'), (2, '2점'), (3, '3점'), (4, '4점'), (5, '5점')], verbose_name='별점')),
                ('running_time', models.IntegerField(verbose_name='러닝타임(분)')),
                ('release_year', models.IntegerField(verbose_name='개봉 년도')),
                ('content', models.TextField(verbose_name='리뷰 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '영화 리뷰',
                'verbose_name_plural': '영화 리뷰들',
                'ordering': ['-created_at'],
            },
        ),
    ]
